default_palette_4bpp = [[20, 14, 30, 255], [45, 26, 113, 255], [50, 87, 190, 255], [64, 157, 239, 255], [112, 219, 255, 255], [191, 255, 255, 255], [62, 50, 213, 255], [110, 106, 255, 255], [166, 173, 255, 255], [216, 224, 255, 255], [101, 43, 188, 255], [180, 76, 239, 255], [236, 140, 255, 255], [255, 205, 255, 255], [72, 14, 85, 255], [148, 24, 135, 255], [228, 68, 195, 255], [255, 145, 226, 255], [25, 12, 18, 255], [85, 14, 43, 255], [175, 16, 46, 255], [255, 66, 79, 255], [255, 151, 146, 255], [255, 213, 207, 255], [73, 29, 30, 255], [170, 44, 30, 255], [246, 109, 30, 255], [255, 174, 104, 255], [255, 225, 181, 255], [73, 41, 23, 255], [151, 83, 15, 255], [221, 140, 0, 255], [251, 200, 0, 255], [255, 246, 153, 255], [12, 16, 27, 255], [14, 62, 18, 255], [56, 116, 26, 255], [108, 179, 40, 255], [175, 227, 86, 255], [228, 252, 162, 255], [13, 56, 76, 255], [23, 117, 120, 255], [0, 188, 159, 255], [107, 236, 189, 255], [201, 252, 204, 255], [53, 50, 52, 255], [102, 93, 91, 255], [153, 141, 134, 255], [205, 191, 179, 255], [234, 230, 218, 255], [47, 49, 67, 255], [80, 93, 109, 255], [123, 149, 160, 255], [166, 207, 208, 255], [223, 234, 228, 255], [141, 65, 49, 255], [203, 115, 77, 255], [239, 175, 121, 255], [156, 43, 59, 255], [228, 87, 97, 255], [255, 255, 255, 255], [0, 0, 0, 255], [228, 22, 43, 255], [255, 255, 64, 255]]

known_textures = {
    "165/34.475/2.9": {
        "unknown": {
            "pos_x": 0,
            "pos_y": 0,
            "whole_sheet": True,
            "palette": default_palette_4bpp,
            "scrambled": False,
            "width": 1024,
            "height": 1024
        }
    },
    "66/11.93/7.9": {
        "unknown2": {
            "pos_x": 0,
            "pos_y": 0,
            "whole_sheet": True,
            "palette": default_palette_4bpp,
            "scrambled": False,
            "width": 1024,
            "height": 1024
        }
    },
    "84/0.57": {
        "deep_space": {
            "scrambled": False,
            "palette_offset": 262784,
            "pos_x": 0,
            "pos_y": 0,
            "width": 256,
            "height": 256
        }
    },
    "93/0.125": {
        "accounts_0": {
            "scrambled": True,
            "palette_offset": 82784,
            "pos_x": 320,
            "pos_y": 64,
            "width": 64,
            "height": 64,
        }
        
    },
    "94/0.125": {
        "accounts_1": {
            "scrambled": True,
            "palette_offset": 65952,
            "pos_x": 512,
            "pos_y": 0,
            "width": 64,
            "height": 64,
        }
    },
    "95/0.125": {
        "accounts_2": {
            "scrambled": True,
            "palette_offset": 49504,
            "pos_x": 320,
            "pos_y": 64,
            "width": 64,
            "height": 64,
        }
    },
    "96/0.125": {
        "accounts_3": {
            "scrambled": True,
            "palette_offset": 17440,
            "pos_x": 512,
            "pos_y": 0,
            "width": 64,
            "height": 64,
        }
    },
    "97/0.125": {
        "accounts_4": {
            "scrambled": True,
            "palette_offset": 50208,
            "pos_x": 320,
            "pos_y": 64,
            "width": 64,
            "height": 64,
        }
    },
    "98/0.125": {
        "accounts_5": {
            "scrambled": True,
            "palette_offset": 33312,
            "pos_x": 512,
            "pos_y": 0,
            "width": 64,
            "height": 64,
        }
    },
    "99/0.125": {
        "notebook": {
            "scrambled": True,
            "palette_offset": 131200,
            "pos_x": 768,
            "pos_y": 64,
            "width": 64,
            "height": 64,
        },
        "weapons": {
            "scrambled": True,
            "palette_offset": 123936,
            "pos_x": 576,
            "pos_y": 64,
            "width": 64,
            "height": 64,
        },
        "equipment": {
            "scrambled": True,
            "palette_offset": 123968,
            "pos_x": 640,
            "pos_y": 64,
            "width": 64,
            "height": 64,
        },
        "usable_items": {
            "scrambled": True,
            "palette_offset": 124000,
            "pos_x": 704,
            "pos_y": 64,
            "width": 64,
            "height": 64,
        },
        "menu_sheet": {
            "scrambled": False,
            "whole_sheet": True,
            "palette_offset": 123968,
            "pos_x": 0,
            "pos_y": 0,
        },
    },
    "108/0.133/12.9": {
        "name_entry_1": {
            "height": 128,
            "palette_offset": 65664,
            "pos_x": 0,
            "pos_y": 0,
            "scrambled": True,
            "width": 512,
        },
        "name_entry_2": {
            "height": 128,
            "palette_offset": 65696,
            "pos_x": 512,
            "pos_y": 0,
            "scrambled": True,
            "width": 512,
        },
    },
    "193/7.559/25.9": {
        "continue_selected": {
            "height": 32,
            "palette_offset": 394304,
            "pos_x": 128,
            "pos_y": 608,
            "scrambled": False,
            "width": 128,
        },
        "continue_unselected": {
            "height": 32,
            "palette_offset": 394240,
            "pos_x": 128,
            "pos_y": 576,
            "scrambled": False,
            "width": 128,
        },
        "enter_selected": {
            "height": 32,
            "palette_offset": 410688,
            "pos_x": 128,
            "pos_y": 736,
            "scrambled": False,
            "width": 128,
        },
        "enter_unselected": {
            "height": 32,
            "palette_offset": 410624,
            "pos_x": 128,
            "pos_y": 704,
            "scrambled": False,
            "width": 128,
        },
        "options_selected": {
            "height": 32,
            "palette_offset": 410560,
            "pos_x": 128,
            "pos_y": 672,
            "scrambled": False,
            "width": 128,
        },
        "options_unselected": {
            "height": 32,
            "palette_offset": 410496,
            "pos_x": 128,
            "pos_y": 640,
            "scrambled": False,
            "width": 128,
        },
        "verdicts_selected": {
            "height": 32,
            "name": "verdicts_selected",
            "palette_offset": 394176,
            "pos_x": 128,
            "pos_y": 544,
            "scrambled": False,
            "width": 128,
        },
        "verdicts_unselected": {
            "height": 32,
            "palette_offset": 394112,
            "pos_x": 128,
            "pos_y": 512,
            "scrambled": False,
            "width": 128,
        },
    },
    "118/0.147": {
        "note_bg_1": {
            "palette_offset": 131712,
            "width": 512,
            "height": 512,
            "pos_x": 0,
            "pos_y": 0,
            "scrambled": False,
            "full_sheet": True
        }
    },
    "108/4.130": {
        "name_entry_char_0": {
            "height": 16,
            "palette_offset": 49664,
            "pos_x": 192,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_1": {
            "height": 16,
            "palette_offset": 49696,
            "pos_x": 256,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_10": {
            "height": 16,
            "palette_offset": 49984,
            "pos_x": 832,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_11": {
            "height": 16,
            "palette_offset": 50016,
            "pos_x": 896,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_12": {
            "height": 16,
            "palette_offset": 50048,
            "pos_x": 960,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_13": {
            "height": 16,
            "palette_offset": 50080,
            "pos_x": 128,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_14": {
            "height": 16,
            "palette_offset": 50112,
            "pos_x": 192,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_15": {
            "height": 16,
            "palette_offset": 50144,
            "pos_x": 256,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_16": {
            "height": 16,
            "palette_offset": 50176,
            "pos_x": 320,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_17": {
            "height": 16,
            "palette_offset": 50208,
            "pos_x": 384,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_18": {
            "height": 16,
            "palette_offset": 50240,
            "pos_x": 448,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_19": {
            "height": 16,
            "palette_offset": 50272,
            "pos_x": 512,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_2": {
            "height": 16,
            "palette_offset": 49728,
            "pos_x": 320,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_20": {
            "height": 16,
            "palette_offset": 57472,
            "pos_x": 576,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_21": {
            "height": 16,
            "palette_offset": 57504,
            "pos_x": 640,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_22": {
            "height": 16,
            "palette_offset": 57536,
            "pos_x": 704,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_23": {
            "height": 16,
            "palette_offset": 57568,
            "pos_x": 768,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_24": {
            "height": 16,
            "palette_offset": 57600,
            "pos_x": 832,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_25": {
            "height": 16,
            "palette_offset": 57632,
            "pos_x": 896,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_26": {
            "height": 16,
            "palette_offset": 57664,
            "pos_x": 960,
            "pos_y": 16,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_27": {
            "height": 16,
            "palette_offset": 57696,
            "pos_x": 0,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_28": {
            "height": 16,
            "palette_offset": 57728,
            "pos_x": 64,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_29": {
            "height": 16,
            "palette_offset": 57760,
            "pos_x": 128,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_3": {
            "height": 16,
            "palette_offset": 49760,
            "pos_x": 384,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_30": {
            "height": 16,
            "palette_offset": 57792,
            "pos_x": 192,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_31": {
            "height": 16,
            "palette_offset": 57824,
            "pos_x": 256,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_32": {
            "height": 16,
            "palette_offset": 57856,
            "pos_x": 320,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_33": {
            "height": 16,
            "palette_offset": 57888,
            "pos_x": 384,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_34": {
            "height": 16,
            "palette_offset": 57920,
            "pos_x": 448,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_35": {
            "height": 16,
            "palette_offset": 57952,
            "pos_x": 512,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_36": {
            "height": 16,
            "palette_offset": 57984,
            "pos_x": 576,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_37": {
            "height": 16,
            "palette_offset": 58016,
            "pos_x": 640,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_38": {
            "height": 16,
            "palette_offset": 58048,
            "pos_x": 704,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_39": {
            "height": 16,
            "palette_offset": 58080,
            "pos_x": 768,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_4": {
            "height": 16,
            "palette_offset": 49792,
            "pos_x": 448,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_40": {
            "height": 16,
            "palette_offset": 58112,
            "pos_x": 832,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_41": {
            "height": 16,
            "palette_offset": 58144,
            "pos_x": 896,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_42": {
            "height": 16,
            "palette_offset": 58176,
            "pos_x": 960,
            "pos_y": 32,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_43": {
            "height": 16,
            "palette_offset": 58208,
            "pos_x": 0,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_44": {
            "height": 16,
            "palette_offset": 58240,
            "pos_x": 64,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_45": {
            "height": 16,
            "palette_offset": 58272,
            "pos_x": 128,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_46": {
            "height": 16,
            "palette_offset": 58304,
            "pos_x": 192,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_47": {
            "height": 16,
            "palette_offset": 58336,
            "pos_x": 256,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_48": {
            "height": 16,
            "palette_offset": 58368,
            "pos_x": 320,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_49": {
            "height": 16,
            "palette_offset": 58400,
            "pos_x": 384,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_5": {
            "height": 16,
            "palette_offset": 49824,
            "pos_x": 512,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_50": {
            "height": 16,
            "palette_offset": 58432,
            "pos_x": 448,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_51": {
            "height": 16,
            "palette_offset": 58464,
            "pos_x": 512,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_52": {
            "height": 16,
            "palette_offset": 65664,
            "pos_x": 576,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_53": {
            "height": 16,
            "palette_offset": 65696,
            "pos_x": 640,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_54": {
            "height": 16,
            "palette_offset": 65728,
            "pos_x": 704,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_55": {
            "height": 16,
            "palette_offset": 65760,
            "pos_x": 768,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_56": {
            "height": 16,
            "palette_offset": 65792,
            "pos_x": 832,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_57": {
            "height": 16,
            "palette_offset": 65824,
            "pos_x": 896,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_58": {
            "height": 16,
            "palette_offset": 65856,
            "pos_x": 960,
            "pos_y": 48,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_59": {
            "height": 16,
            "palette_offset": 65888,
            "pos_x": 0,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_6": {
            "height": 16,
            "palette_offset": 49856,
            "pos_x": 576,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_60": {
            "height": 16,
            "palette_offset": 65920,
            "pos_x": 64,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_61": {
            "height": 16,
            "palette_offset": 65952,
            "pos_x": 128,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_62": {
            "height": 16,
            "palette_offset": 65984,
            "pos_x": 192,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_63": {
            "height": 16,
            "palette_offset": 66016,
            "pos_x": 256,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_64": {
            "height": 16,
            "palette_offset": 66048,
            "pos_x": 320,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_65": {
            "height": 16,
            "palette_offset": 66080,
            "pos_x": 384,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_66": {
            "height": 16,
            "palette_offset": 66112,
            "pos_x": 448,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_67": {
            "height": 16,
            "palette_offset": 66144,
            "pos_x": 512,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_68": {
            "height": 16,
            "palette_offset": 66176,
            "pos_x": 576,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_69": {
            "height": 16,
            "palette_offset": 66208,
            "pos_x": 640,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_7": {
            "height": 16,
            "palette_offset": 49888,
            "pos_x": 640,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_70": {
            "height": 16,
            "palette_offset": 66240,
            "pos_x": 704,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_71": {
            "height": 16,
            "palette_offset": 66272,
            "pos_x": 768,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_72": {
            "height": 16,
            "palette_offset": 66304,
            "pos_x": 832,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_73": {
            "height": 16,
            "palette_offset": 66336,
            "pos_x": 896,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_74": {
            "height": 16,
            "palette_offset": 66368,
            "pos_x": 960,
            "pos_y": 64,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_75": {
            "height": 16,
            "palette_offset": 66400,
            "pos_x": 0,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_76": {
            "height": 16,
            "palette_offset": 66432,
            "pos_x": 64,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_77": {
            "height": 16,
            "palette_offset": 66464,
            "pos_x": 128,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_78": {
            "height": 16,
            "palette_offset": 66496,
            "pos_x": 192,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_79": {
            "height": 16,
            "palette_offset": 66528,
            "pos_x": 256,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_8": {
            "height": 16,
            "palette_offset": 49920,
            "pos_x": 704,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_80": {
            "height": 16,
            "palette_offset": 66560,
            "pos_x": 320,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_81": {
            "height": 16,
            "palette_offset": 66592,
            "pos_x": 384,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_82": {
            "height": 16,
            "palette_offset": 66624,
            "pos_x": 448,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_83": {
            "height": 16,
            "palette_offset": 66656,
            "pos_x": 512,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_84": {
            "height": 16,
            "palette_offset": 73856,
            "pos_x": 576,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_85": {
            "height": 16,
            "palette_offset": 73888,
            "pos_x": 640,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_86": {
            "height": 16,
            "palette_offset": 73920,
            "pos_x": 704,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_87": {
            "height": 16,
            "palette_offset": 73952,
            "pos_x": 768,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_88": {
            "height": 16,
            "palette_offset": 73984,
            "pos_x": 832,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_89": {
            "height": 16,
            "palette_offset": 74016,
            "pos_x": 896,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_9": {
            "height": 16,
            "palette_offset": 49952,
            "pos_x": 768,
            "pos_y": 0,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_90": {
            "height": 16,
            "palette_offset": 74048,
            "pos_x": 960,
            "pos_y": 80,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_91": {
            "height": 16,
            "palette_offset": 74080,
            "pos_x": 0,
            "pos_y": 96,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_92": {
            "height": 16,
            "palette_offset": 74112,
            "pos_x": 64,
            "pos_y": 96,
            "scrambled": "true",
            "width": 64,
        },
        "name_entry_char_93": {
            "height": 16,
            "palette_offset": 74144,
            "pos_x": 128,
            "pos_y": 96,
            "scrambled": "true",
            "width": 64,
        },
    },
}
